# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-17 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='conclusion',
            field=models.TextField(null=True),
        ),
    ]
